version: 2
updates:
  - package-ecosystem: npm
    directory: "/Monologue"
    target-branch: dev
    open-pull-requests-limit: 15
    schedule:
      interval: weekly
  - package-ecosystem: gradle
    directory: "/Monolith"
    target-branch: dev
    open-pull-requests-limit: 15
    schedule:
      interval: weekly
