name: Build

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - uses: actions/setup-java@v4.3.0
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4.1.0
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cd Monolith
          chmod +x ./gradlew
          ./gradlew publish -x test
          mv build/libs/mono-unit*.jar ../
          cd ..

      - name: Archive Dist
        run: |
          cd Monologue
          rm -rf public
          mv dist public
          zip -r monologue-view.zip public
          mv monologue-view.zip ../
          cd ..

      - name: Release
        uses: ncipollo/release-action@v1.14.0
        with:
          name: TestBuild
          artifacts: "mono-unit.jar,mono-unit-plain.jar,monologue-view.zip"
          tag: "prebuild"
          allowUpdates: true
          prerelease: true
          body: "TestBuild for dev"
